### ISSUE TITLE
Website homepage

### ISSUE THREAD

**Issue by mtt87** [ItalianiDigitaliLondra/WhatWeWantToDo#1]
In my opinion we have to write something about
- What is this group? 
- What we do? 
- How can you join? 
- How can you contribute?

Nicola sent me a few pictures that we can possibly use for the website
![screen shot 2015-02-16 at 00 54 51](https://cloud.githubusercontent.com/assets/2150927/6205923/e5429ac6-b576-11e4-8675-f873ea7e7f51.png)

**Comment by danieledangeli** [comment]
I love that logo :dancer:
